name: Docs

on:
  push:
    branches:
      - master
      - v4-dev
  pull_request:
    branches:
      - "**"

env:
  FORCE_COLOR: 2
  NODE: 16.x
  RUBY: 2.7

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - name: Set up Node.js
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2
        with:
          node-version: "${{ env.NODE }}"

      - name: Set up Ruby
        uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1
        with:
          ruby-version: "${{ env.RUBY }}"
          bundler-cache: true
          working-directory: docs

      - name: Version info
        run: |
          ruby --version
          gem --version
          bundle --version
          java -version

      - name: Set up npm cache
        uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-v${{ env.NODE }}-${{ hashFiles('package.json') }}-${{ hashFiles('package-lock.json') }}}
          restore-keys: |
            ${{ runner.os }}-node-v${{ env.NODE }}-${{ hashFiles('package.json') }}-${{ hashFiles('package-lock.json') }}
            ${{ runner.os }}-node-v${{ env.NODE }}-

      - name: Install npm dependencies
        run: npm ci

      - name: Build docs
        run: npm run docs-compile

      - name: Run HTML validator
        run: npm run docs-lint
